"""
Theme to Major Theme Category Mapping
Used to automatically assign major themes to books based on their individual themes.
"""

# Major theme categories
MAJOR_THEMES = [
    "Human Condition & Emotions",
    "Identity & Self",
    "Personal Growth & Resilience",
    "Family & Relationships",
    "Morality & Ethics",
    "Faith & Spirituality",
    "Music & Arts",
    "Philosophy & Ideas",
    "Politics & Power",
    "War & Conflict",
    "Society & Culture",
    "Social Justice & Equality",
    "Business & Leadership",
    "Science & Technology",
    "Psychology & Behavior",
    "Nature & Environment",
    "Sports & Competition",
]

# Mapping of individual themes to major theme categories
# A theme can map to multiple categories; the first match wins when assigning
THEME_TO_MAJOR = {
    # Human Condition & Emotions
    "absurdism": "Human Condition & Emotions",
    "addiction": "Human Condition & Emotions",
    "aging": "Human Condition & Emotions",
    "alienation": "Human Condition & Emotions",
    "belonging": "Human Condition & Emotions",
    "compassion": "Human Condition & Emotions",
    "death": "Human Condition & Emotions",
    "desire": "Human Condition & Emotions",
    "despair": "Human Condition & Emotions",
    "dignity": "Human Condition & Emotions",
    "discomfort": "Human Condition & Emotions",
    "doubt": "Human Condition & Emotions",
    "dreams": "Human Condition & Emotions",
    "dreams and aspirations": "Human Condition & Emotions",
    "dreams vs. reality": "Human Condition & Emotions",
    "existential disorientation": "Human Condition & Emotions",
    "fate": "Human Condition & Emotions",
    "grief": "Human Condition & Emotions",
    "guilt": "Human Condition & Emotions",
    "happiness": "Human Condition & Emotions",
    "hope": "Human Condition & Emotions",
    "hope amidst turmoil": "Human Condition & Emotions",
    "human condition": "Human Condition & Emotions",
    "human connection": "Human Condition & Emotions",
    "human endurance": "Human Condition & Emotions",
    "human nature": "Human Condition & Emotions",
    "human psyche": "Human Condition & Emotions",
    "human spirit": "Human Condition & Emotions",
    "humility": "Human Condition & Emotions",
    "humor": "Human Condition & Emotions",
    "hysteria": "Human Condition & Emotions",
    "isolation": "Human Condition & Emotions",
    "loneliness": "Human Condition & Emotions",
    "loss": "Human Condition & Emotions",
    "love": "Human Condition & Emotions",
    "love and desire": "Human Condition & Emotions",
    "love and rejection": "Human Condition & Emotions",
    "madness": "Human Condition & Emotions",
    "meaning of life": "Human Condition & Emotions",
    "memory": "Human Condition & Emotions",
    "nostalgia": "Human Condition & Emotions",
    "obsession": "Human Condition & Emotions",
    "passion": "Human Condition & Emotions",
    "reality vs. illusion": "Human Condition & Emotions",
    "regret": "Human Condition & Emotions",
    "sacrifice": "Human Condition & Emotions",
    "search for meaning": "Human Condition & Emotions",
    "suffering": "Human Condition & Emotions",
    "the human condition": "Human Condition & Emotions",
    "time": "Human Condition & Emotions",
    "time and memory": "Human Condition & Emotions",
    "tragedy": "Human Condition & Emotions",
    "truth": "Human Condition & Emotions",
    "uncertainty": "Human Condition & Emotions",
    
    # Identity & Self
    "ambition": "Identity & Self",
    "ambition and self-improvement": "Identity & Self",
    "character development": "Identity & Self",
    "conformity vs individuality": "Identity & Self",
    "consciousness": "Identity & Self",
    "creativity": "Identity & Self",
    "curiosity": "Identity & Self",
    "gender bias": "Identity & Self",
    "genius": "Identity & Self",
    "homosexuality": "Identity & Self",
    "identity": "Identity & Self",
    "identity and belonging": "Identity & Self",
    "imagination": "Identity & Self",
    "individual vs. society": "Identity & Self",
    "individuality": "Identity & Self",
    "masculinity": "Identity & Self",
    "native american identity": "Identity & Self",
    "non-conformity": "Identity & Self",
    "nonconformity": "Identity & Self",
    "personal journey": "Identity & Self",
    "personal legacy": "Identity & Self",
    "personal legend": "Identity & Self",
    "personal reflection": "Identity & Self",
    "racial identity": "Identity & Self",
    "self-discovery": "Identity & Self",
    "the lost generation": "Identity & Self",
    
    # Personal Growth & Resilience
    "adaptation": "Personal Growth & Resilience",
    "behavior change": "Personal Growth & Resilience",
    "change": "Personal Growth & Resilience",
    "courage": "Personal Growth & Resilience",
    "effectiveness": "Personal Growth & Resilience",
    "empowerment": "Personal Growth & Resilience",
    "endurance": "Personal Growth & Resilience",
    "focus": "Personal Growth & Resilience",
    "growth mindset": "Personal Growth & Resilience",
    "habit formation": "Personal Growth & Resilience",
    "healing": "Personal Growth & Resilience",
    "inner growth": "Personal Growth & Resilience",
    "life experiences": "Personal Growth & Resilience",
    "life lessons": "Personal Growth & Resilience",
    "life planning": "Personal Growth & Resilience",
    "mental resilience": "Personal Growth & Resilience",
    "moral formation": "Personal Growth & Resilience",
    "moral growth": "Personal Growth & Resilience",
    "overcoming adversity": "Personal Growth & Resilience",
    "perseverance": "Personal Growth & Resilience",
    "personal development": "Personal Growth & Resilience",
    "personal growth": "Personal Growth & Resilience",
    "problem-solving": "Personal Growth & Resilience",
    "productivity": "Personal Growth & Resilience",
    "resilience": "Personal Growth & Resilience",
    "self-discipline": "Personal Growth & Resilience",
    "self-improvement": "Personal Growth & Resilience",
    "self-sacrifice": "Personal Growth & Resilience",
    "selflessness": "Personal Growth & Resilience",
    "success": "Personal Growth & Resilience",
    "time management": "Personal Growth & Resilience",
    "transformation": "Personal Growth & Resilience",
    "triumph over adversity": "Personal Growth & Resilience",
    "work habits": "Personal Growth & Resilience",
    "workplace effectiveness": "Personal Growth & Resilience",
    
    # Family & Relationships
    "betrayal": "Family & Relationships",
    "brotherhood": "Family & Relationships",
    "community": "Family & Relationships",
    "family": "Family & Relationships",
    "family and its complexities": "Family & Relationships",
    "family conflict": "Family & Relationships",
    "family history": "Family & Relationships",
    "family legacy": "Family & Relationships",
    "family secrets": "Family & Relationships",
    "family values": "Family & Relationships",
    "fatherhood": "Family & Relationships",
    "friendship": "Family & Relationships",
    "loyalty": "Family & Relationships",
    "marriage": "Family & Relationships",
    "marriage and fidelity": "Family & Relationships",
    "reconciliation": "Family & Relationships",
    "team dynamics": "Family & Relationships",
    "teamwork": "Family & Relationships",
    
    # Morality & Ethics
    "accountability": "Morality & Ethics",
    "chivalry": "Morality & Ethics",
    "crime": "Morality & Ethics",
    "crime and guilt": "Morality & Ethics",
    "deception": "Morality & Ethics",
    "duty and service": "Morality & Ethics",
    "ethics of technology": "Morality & Ethics",
    "honor": "Morality & Ethics",
    "injustice": "Morality & Ethics",
    "integrity": "Morality & Ethics",
    "justice": "Morality & Ethics",
    "justice and law": "Morality & Ethics",
    "justice and the legal system": "Morality & Ethics",
    "knowledge vs ignorance": "Morality & Ethics",
    "legalism": "Morality & Ethics",
    "mercy": "Morality & Ethics",
    "moral struggle": "Morality & Ethics",
    "moral virtues": "Morality & Ethics",
    "morality": "Morality & Ethics",
    "redemption": "Morality & Ethics",
    "responsibility": "Morality & Ethics",
    "revenge": "Morality & Ethics",
    "sin": "Morality & Ethics",
    "sin and virtue": "Morality & Ethics",
    "theological ethics": "Morality & Ethics",
    "truth and deception": "Morality & Ethics",
    "vice and corruption": "Morality & Ethics",
    "virtue": "Morality & Ethics",
    
    # Faith & Spirituality
    "afterlife": "Faith & Spirituality",
    "authentic faith": "Faith & Spirituality",
    "belief": "Faith & Spirituality",
    "christian hope": "Faith & Spirituality",
    "christian virtue": "Faith & Spirituality",
    "critique of formulaic religion": "Faith & Spirituality",
    "divine grace": "Faith & Spirituality",
    "eschatology": "Faith & Spirituality",
    "faith": "Faith & Spirituality",
    "faith and doubt": "Faith & Spirituality",
    "faith and spirituality": "Faith & Spirituality",
    "forgiveness": "Faith & Spirituality",
    "grace": "Faith & Spirituality",
    "humanitarian aid": "Faith & Spirituality",
    "intimacy with god": "Faith & Spirituality",
    "mission": "Faith & Spirituality",
    "peace and reconciliation": "Faith & Spirituality",
    "relationship with god": "Faith & Spirituality",
    "religion": "Faith & Spirituality",
    "resurrection": "Faith & Spirituality",
    "service": "Faith & Spirituality",
    "service to others": "Faith & Spirituality",
    "sovereignty of god": "Faith & Spirituality",
    "spiritual growth": "Faith & Spirituality",
    "spiritual journey": "Faith & Spirituality",
    "spiritual struggle": "Faith & Spirituality",
    "spirituality": "Faith & Spirituality",
    
    # Music & Arts
    "art": "Music & Arts",
    "artistic legacy": "Music & Arts",
    "bebop": "Music & Arts",
    "celebrity": "Music & Arts",
    "celebrity culture": "Music & Arts",
    "collaboration": "Music & Arts",
    "craft cocktails": "Music & Arts",
    "creative process": "Music & Arts",
    "drink recipes": "Music & Arts",
    "improvisation": "Music & Arts",
    "innovations in music": "Music & Arts",
    "jazz": "Music & Arts",
    "jazz education": "Music & Arts",
    "jazz history": "Music & Arts",
    "jazz music": "Music & Arts",
    "mixology": "Music & Arts",
    "music": "Music & Arts",
    "music history": "Music & Arts",
    "musical creativity": "Music & Arts",
    "musical genius": "Music & Arts",
    "musical innovation": "Music & Arts",
    "musician's life": "Music & Arts",
    "narrative perspectives": "Music & Arts",
    "power of storytelling": "Music & Arts",
    "bartending": "Music & Arts",
    
    # Philosophy & Ideas
    "chaos and order": "Philosophy & Ideas",
    "dualism": "Philosophy & Ideas",
    "existentialism": "Philosophy & Ideas",
    "free will": "Philosophy & Ideas",
    "impermanence": "Philosophy & Ideas",
    "nature vs. nurture": "Philosophy & Ideas",
    "perception": "Philosophy & Ideas",
    "philosophy": "Philosophy & Ideas",
    "primitivism and civilization": "Philosophy & Ideas",
    "rationality": "Philosophy & Ideas",
    "stoicism": "Philosophy & Ideas",
    
    # Politics & Power
    "authority and rebellion": "Politics & Power",
    "bureaucracy": "Politics & Power",
    "capitalism": "Politics & Power",
    "censorship": "Politics & Power",
    "colonialism": "Politics & Power",
    "control": "Politics & Power",
    "corporate power": "Politics & Power",
    "corruption": "Politics & Power",
    "decline of empire": "Politics & Power",
    "globalization": "Politics & Power",
    "leadership": "Politics & Power",
    "political conflict": "Politics & Power",
    "political history": "Politics & Power",
    "political intrigue": "Politics & Power",
    "political power": "Politics & Power",
    "politics": "Politics & Power",
    "power": "Politics & Power",
    "power and authority": "Politics & Power",
    "power and influence": "Politics & Power",
    "public policy": "Politics & Power",
    "revolution": "Politics & Power",
    "societal reform": "Politics & Power",
    "surveillance": "Politics & Power",
    "totalitarianism": "Politics & Power",
    "urban development": "Politics & Power",
    "urban planning": "Politics & Power",
    
    # War & Conflict
    "conflict": "War & Conflict",
    "conflict and displacement": "War & Conflict",
    "heroism": "War & Conflict",
    "military history": "War & Conflict",
    "peace": "War & Conflict",
    "resistance": "War & Conflict",
    "revolutionary war": "War & Conflict",
    "strategy": "War & Conflict",
    "struggle": "War & Conflict",
    "struggle for survival": "War & Conflict",
    "survival": "War & Conflict",
    "war": "War & Conflict",
    "warfare": "War & Conflict",
    
    # Society & Culture
    "american culture": "Society & Culture",
    "american dream": "Society & Culture",
    "american history": "Society & Culture",
    "american identity": "Society & Culture",
    "class": "Society & Culture",
    "class and society": "Society & Culture",
    "class disparity": "Society & Culture",
    "class struggle": "Society & Culture",
    "cultural adaptation": "Society & Culture",
    "cultural change": "Society & Culture",
    "cultural clashes": "Society & Culture",
    "cultural conflict": "Society & Culture",
    "cultural differences": "Society & Culture",
    "cultural displacement": "Society & Culture",
    "cultural evolution": "Society & Culture",
    "cultural heritage": "Society & Culture",
    "cultural influence": "Society & Culture",
    "cultural preservation": "Society & Culture",
    "cultural survival": "Society & Culture",
    "culture": "Society & Culture",
    "decline of southern aristocracy": "Society & Culture",
    "displacement": "Society & Culture",
    "folklore": "Society & Culture",
    "frontier experience": "Society & Culture",
    "frontier life": "Society & Culture",
    "immigration": "Society & Culture",
    "mythology": "Society & Culture",
    "new york city": "Society & Culture",
    "settlement": "Society & Culture",
    "social change": "Society & Culture",
    "social class": "Society & Culture",
    "social commentary": "Society & Culture",
    "social epidemics": "Society & Culture",
    "social mobility": "Society & Culture",
    "society": "Society & Culture",
    "society and class": "Society & Culture",
    "the american dream": "Society & Culture",
    "the impact of industrialization": "Society & Culture",
    "tradition": "Society & Culture",
    "travel": "Society & Culture",
    "cuisine": "Society & Culture",
    
    # Social Justice & Equality
    "activism": "Social Justice & Equality",
    "poverty": "Social Justice & Equality",
    "race": "Social Justice & Equality",
    "race and culture": "Social Justice & Equality",
    "race and ethnicity": "Social Justice & Equality",
    "race and racism": "Social Justice & Equality",
    "racial injustice": "Social Justice & Equality",
    "racism": "Social Justice & Equality",
    "racism and slavery": "Social Justice & Equality",
    "slavery": "Social Justice & Equality",
    "social injustice": "Social Justice & Equality",
    "systemic inequality": "Social Justice & Equality",
    "women's rights": "Social Justice & Equality",
    
    # Business & Leadership
    "acceleration": "Business & Leadership",
    "business strategy": "Business & Leadership",
    "decision making": "Business & Leadership",
    "decision-making": "Business & Leadership",
    "disruptive innovation": "Business & Leadership",
    "economic development": "Business & Leadership",
    "economics": "Business & Leadership",
    "employee engagement": "Business & Leadership",
    "financial ingenuity": "Business & Leadership",
    "financial strategy": "Business & Leadership",
    "innovation": "Business & Leadership",
    "innovation adoption": "Business & Leadership",
    "luck vs. skill": "Business & Leadership",
    "management": "Business & Leadership",
    "market leadership": "Business & Leadership",
    "organizational change": "Business & Leadership",
    "planning": "Business & Leadership",
    "quality": "Business & Leadership",
    "reputation": "Business & Leadership",
    "risk": "Business & Leadership",
    "talent vs. effort": "Business & Leadership",
    "technology marketing": "Business & Leadership",
    "underdogs": "Business & Leadership",
    "wealth": "Business & Leadership",
    "wealth management": "Business & Leadership",
    
    # Science & Technology
    "artificial intelligence": "Science & Technology",
    "contagion": "Science & Technology",
    "data analysis": "Science & Technology",
    "data gap": "Science & Technology",
    "data presentation": "Science & Technology",
    "data visualization": "Science & Technology",
    "evolution": "Science & Technology",
    "evolution of societies": "Science & Technology",
    "existential risk": "Science & Technology",
    "geographical determinism": "Science & Technology",
    "graphic representation": "Science & Technology",
    "history of mathematics": "Science & Technology",
    "impact of agriculture": "Science & Technology",
    "information clarity": "Science & Technology",
    "information design": "Science & Technology",
    "intelligence": "Science & Technology",
    "machine learning": "Science & Technology",
    "mathematics": "Science & Technology",
    "mechanics": "Science & Technology",
    "probability": "Science & Technology",
    "programming": "Science & Technology",
    "robotics": "Science & Technology",
    "scientific discovery": "Science & Technology",
    "statistical graphics": "Science & Technology",
    "statistics": "Science & Technology",
    "technological change": "Science & Technology",
    "technology": "Science & Technology",
    "technology vs. humanity": "Science & Technology",
    "visual communication": "Science & Technology",
    "web development": "Science & Technology",
    
    # Psychology & Behavior
    "attention": "Psychology & Behavior",
    "behavioral science": "Psychology & Behavior",
    "exercise and mental health": "Psychology & Behavior",
    "insight": "Psychology & Behavior",
    "mental health": "Psychology & Behavior",
    "neuroscience": "Psychology & Behavior",
    "power of the mind": "Psychology & Behavior",
    "psychological insight": "Psychology & Behavior",
    "psychological struggle": "Psychology & Behavior",
    "psychology": "Psychology & Behavior",
    
    # Nature & Environment
    "environmental change": "Nature & Environment",
    "environmentalism": "Nature & Environment",
    "exploration": "Nature & Environment",
    "humanity vs nature": "Nature & Environment",
    "interconnection of life": "Nature & Environment",
    "man vs. nature": "Nature & Environment",
    "nature": "Nature & Environment",
    "nature of greatness": "Nature & Environment",
    "nature vs humanity": "Nature & Environment",
    "adventure": "Nature & Environment",
    "escape": "Nature & Environment",
    
    # Sports & Competition
    "baseball": "Sports & Competition",
    "sports": "Sports & Competition",
    "sports evolution": "Sports & Competition",
    "sports history": "Sports & Competition",
    
    # Misc/catch-all mappings
    "alchemy": "Philosophy & Ideas",
    "analytical design": "Science & Technology",
    "complexity": "Philosophy & Ideas",
    "confinement": "Human Condition & Emotions",
    "design thinking": "Business & Leadership",
    "education": "Personal Growth & Resilience",
    "freedom": "Human Condition & Emotions",
    "historical analysis": "Society & Culture",
    "history": "Society & Culture",
    "human cost": "Human Condition & Emotions",
    "legacy": "Human Condition & Emotions",
}


def get_major_theme(themes_list):
    """
    Given a list of themes, determine the most appropriate major theme.
    Returns the major theme that appears most frequently among the book's themes.
    """
    if not themes_list:
        return None
    
    # Count occurrences of each major theme
    major_counts = {}
    for theme in themes_list:
        theme_lower = theme.lower().strip()
        if theme_lower in THEME_TO_MAJOR:
            major = THEME_TO_MAJOR[theme_lower]
            major_counts[major] = major_counts.get(major, 0) + 1
    
    if not major_counts:
        return None
    
    # Return the major theme with the highest count
    return max(major_counts, key=major_counts.get)


def get_all_major_themes(themes_list):
    """
    Given a list of themes, return all unique major themes (for display purposes).
    """
    if not themes_list:
        return []
    
    majors = set()
    for theme in themes_list:
        theme_lower = theme.lower().strip()
        if theme_lower in THEME_TO_MAJOR:
            majors.add(THEME_TO_MAJOR[theme_lower])
    
    return sorted(majors)
